### ISSUE TITLE
Make instance name configurable

### ISSUE THREAD

**Issue by c00kiemon5ter** [dylex/xtmux#22]
`XClassHint` allows to set the application _class name_ and _instance name_. Most terminals allow to manually specify the instance name (ie `urxvt` has `-name` switch). 
This would be nice to have, as some window managers based on this value allow for different behavior (special management of that window).

**Comment by c00kiemon5ter** [comment]
I thought [this](https://gist.github.com/3812222) would do it, but it seems not. 
I kind of baffled as to why `xtmux_open` doesn't seems to be called here. 
Anyway, you know better. Take a look when you have the time.

**Comment by dylex** [comment]
Ah, yeah this is probably better done with a new option, probably a client option.

**Comment by dylex** [comment]
I've added a new client option, "xtmux-name", which will set the resource name.  Let me know if this works for you.

(Again, sorry it took me so long to notice this.)

**Comment by c00kiemon5ter** [comment]
it works as expected. thanks. 

btw, github changed the mail settings in some recent changes.
read about it [here](https://github.com/blog/1204-notifications-stars) and check [this](https://github.com/settings/notifications)
